### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.core.exceptions.AzureError
  - azure.core.exceptions.ClientAuthenticationError
  - azure.core.exceptions.DecodeError
  - azure.core.exceptions.HttpResponseError
  - azure.core.exceptions.ODataV4Error
  - azure.core.exceptions.ODataV4Format
  - azure.core.exceptions.ResourceExistsError
  - azure.core.exceptions.ResourceModifiedError
  - azure.core.exceptions.ResourceNotFoundError
  - azure.core.exceptions.ServiceRequestError
  - azure.core.exceptions.ServiceResponseError
  - azure.core.exceptions.TooManyRedirectsError
  - azure.core.exceptions.map_error
  - azure.core.exceptions.raise_with_traceback
  fullName: azure.core.exceptions
  langs:
  - python
  module: azure.core.exceptions
  name: exceptions
  type: module
  uid: azure.core.exceptions
- fullName: azure.core.exceptions.map_error
  langs:
  - python
  module: azure.core.exceptions
  name: map_error(status_code, response, error_map)
  syntax:
    content: map_error(status_code, response, error_map)
    parameters:
    - id: status_code
    - id: response
    - id: error_map
  type: function
  uid: azure.core.exceptions.map_error
- fullName: azure.core.exceptions.raise_with_traceback
  langs:
  - python
  module: azure.core.exceptions
  name: raise_with_traceback(exception, *args, **kwargs)
  summary: 'Raise exception with a specified traceback.

    This MUST be called inside a "except" clause.


    **Keyword argument:**


    *message (str)* - Message to be associated with the exception. If omitted, defaults
    to an empty string.'
  syntax:
    content: raise_with_traceback(exception, *args, **kwargs)
    parameters:
    - description: Error type to be raised.
      id: exception
      type:
      - Exception
    - description: Any additional args to be included with exception.
      id: args
    - description: Keyword arguments to include with the exception.
      id: kwargs
  type: function
  uid: azure.core.exceptions.raise_with_traceback
references:
- fullName: azure.core.exceptions.AzureError
  isExternal: false
  name: AzureError
  parent: azure.core.exceptions
  uid: azure.core.exceptions.AzureError
- fullName: azure.core.exceptions.ClientAuthenticationError
  isExternal: false
  name: ClientAuthenticationError
  parent: azure.core.exceptions
  uid: azure.core.exceptions.ClientAuthenticationError
- fullName: azure.core.exceptions.DecodeError
  isExternal: false
  name: DecodeError
  parent: azure.core.exceptions
  uid: azure.core.exceptions.DecodeError
- fullName: azure.core.exceptions.HttpResponseError
  isExternal: false
  name: HttpResponseError
  parent: azure.core.exceptions
  uid: azure.core.exceptions.HttpResponseError
- fullName: azure.core.exceptions.ODataV4Error
  isExternal: false
  name: ODataV4Error
  parent: azure.core.exceptions
  uid: azure.core.exceptions.ODataV4Error
- fullName: azure.core.exceptions.ODataV4Format
  isExternal: false
  name: ODataV4Format
  parent: azure.core.exceptions
  uid: azure.core.exceptions.ODataV4Format
- fullName: azure.core.exceptions.ResourceExistsError
  isExternal: false
  name: ResourceExistsError
  parent: azure.core.exceptions
  uid: azure.core.exceptions.ResourceExistsError
- fullName: azure.core.exceptions.ResourceModifiedError
  isExternal: false
  name: ResourceModifiedError
  parent: azure.core.exceptions
  uid: azure.core.exceptions.ResourceModifiedError
- fullName: azure.core.exceptions.ResourceNotFoundError
  isExternal: false
  name: ResourceNotFoundError
  parent: azure.core.exceptions
  uid: azure.core.exceptions.ResourceNotFoundError
- fullName: azure.core.exceptions.ServiceRequestError
  isExternal: false
  name: ServiceRequestError
  parent: azure.core.exceptions
  uid: azure.core.exceptions.ServiceRequestError
- fullName: azure.core.exceptions.ServiceResponseError
  isExternal: false
  name: ServiceResponseError
  parent: azure.core.exceptions
  uid: azure.core.exceptions.ServiceResponseError
- fullName: azure.core.exceptions.TooManyRedirectsError
  isExternal: false
  name: TooManyRedirectsError
  parent: azure.core.exceptions
  uid: azure.core.exceptions.TooManyRedirectsError
- fullName: azure.core.exceptions.map_error
  isExternal: false
  name: map_error(status_code, response, error_map)
  parent: azure.core.exceptions
  uid: azure.core.exceptions.map_error
- fullName: azure.core.exceptions.raise_with_traceback
  isExternal: false
  name: raise_with_traceback(exception, *args, **kwargs)
  parent: azure.core.exceptions
  uid: azure.core.exceptions.raise_with_traceback
